### ISSUE TITLE
Tracking issues of Iceberg Rust 0.2.0 Release

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#180]
This issue is used to track tasks of the iceberg rust 0.2.0 release, see [discussion](https://lists.apache.org/thread/8sj66kf02qd0qtyyrj4gox3yozjk3vtd) in community here.

### Blockers

- [x] #174 
- [x] #183 
- [x] #182 

#### GitHub Side

- [x] Bump version in project
- [x] Update docs
- [x] Generate dependencies list
- [x] Push release candidate tag to GitHub

#### ASF Side

- [x] Create an ASF Release
- [x] Upload artifacts to the SVN dist repo

### Voting

- [x] Start VOTE at iceberg community

### Official Release

- [x] Push the release git tag
- [x] Publish artifacts to SVN RELEASE branch
- [x] Change Iceberg Rust Website download link
- [x] Publish to crates.io
- [x] Send the announcement

**Comment by Xuanwo** [comment]
Blocker: https://github.com/apache/iceberg-rust/pull/174

**Comment by Fokko** [comment]
I think we're ready for a release. Do we want to get in https://github.com/apache/iceberg-rust/pull/193 as well?

**Comment by liurenjie1024** [comment]
> I think we're ready for a release. Do we want to get in https://github.com/apache/iceberg-rust/pull/193 as well? 

Yes, it will make the env setup error more user friendly.

**Comment by liurenjie1024** [comment]
Voting passed: https://lists.apache.org/thread/1rnk9c1ldjhd160bfxvdyk7mlkzrjj03

**Comment by liurenjie1024** [comment]
Updated the issue to add an extra step: upload to crates.io. cc @Xuanwo @Fokko

**Comment by liurenjie1024** [comment]
FYI, here is the doc for publishing on crates.io: https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate

**Comment by liurenjie1024** [comment]
Close this issue since all steps have finished, thanks everyone's effort!
