### ISSUE TITLE
Implement Glue Catalog

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#249]
Implement glue catalog.

**Comment by liurenjie1024** [comment]
Blocked by #250

**Comment by marvinlanhenke** [comment]
@liurenjie1024 
... I started prototyping on this, here is what I'm trying to do:
## Tasks:
- [ ] Setup basic structure + test infra
- [ ] Implement namespace operations
- [ ] Implement table operations

**Comment by liurenjie1024** [comment]
Hi, @marvinlanhenke Thanks for this. I'm curious how do you plan to setup test infra for glue? It seems that there is no docker for glue?

**Comment by marvinlanhenke** [comment]
> I'm curious how do you plan to setup test infra for glue? It seems that there is no docker for glue?

I looked at the pyiceberg tests and saw that here `moto` is used.
Moto provides a docker-compose to mock most of AWS Services / I tested this with a quick prototype and it seems to work fine in conjunction with the AWS SDK Rust.

https://github.com/apache/iceberg-python/blob/main/tests/catalog/test_glue.py#L23
https://docs.getmoto.org/en/latest/docs/server_mode.html#run-using-docker

**Comment by liurenjie1024** [comment]
> > I'm curious how do you plan to setup test infra for glue? It seems that there is no docker for glue?
> 
> I looked at the pyiceberg tests which utilize `moto`. Moto provides a docker-compose to mock most of AWS Services / I tested this with a quick prototype and it seems to work fine in conjunction with the AWS SDK Rust.
> 
> https://github.com/apache/iceberg-python/blob/main/tests/catalog/test_glue.py#L23 https://docs.getmoto.org/en/latest/docs/server_mode.html#run-using-docker

That's great! Thanks!
