### ISSUE TITLE
Tracking:: Writing iceberg tables

### ISSUE THREAD

**Issue by ZENOTME** [apache/iceberg-rust#346]
Inspired by https://github.com/apache/iceberg-rust/pull/275#issuecomment-2041304545, I created this issue to track all our write task. It's based on [doc](https://docs.google.com/document/d/1YncDX-qQ1T9jBGQmJNtRcPU1trRi00cB8eykv5diKw4/edit?usp=sharing).

- [ ] https://github.com/apache/iceberg-rust/issues/345
- [ ] https://github.com/apache/iceberg-rust/issues/329
- [ ] Overwrite table
- [ ] https://github.com/apache/iceberg-rust/issues/342
- [ ] https://github.com/apache/iceberg-rust/issues/340
- [ ] https://github.com/apache/iceberg-rust/issues/341
- [ ] https://github.com/apache/iceberg-rust/issues/343

**Comment by c-thiel** [comment]
Dear all,
we have been talking to many people recently that are working in the Rust data ecosystem for which writes or compaction would be very important. Many are also willing to take up some of the issues here - me included.

My goal is to align with the community on good next steps and then distribute issues among us to get more focus, attention and developer time for the issues that are needed to implement writes and compaction.

In addition to the issues listed above, there are currently open PRs that are also important for writes:

**Related PRs in `iceberg-rust`**
- https://github.com/apache/iceberg-rust/pull/349 (thanks @ZENOTME, contains fast append)
- https://github.com/apache/iceberg-rust/pull/587
- https://github.com/apache/iceberg-rust/pull/652 (thanks @sdd) - Issue https://github.com/apache/iceberg-rust/issues/630

**Related other Issues / Discussions**
- https://github.com/apache/iceberg-rust/issues/329, related also this [doc](https://docs.google.com/document/d/1YncDX-qQ1T9jBGQmJNtRcPU1trRi00cB8eykv5diKw4/edit?usp=sharing) (thanks @liurenjie1024)
- https://github.com/apache/iceberg-rust/issues/657 (thanks @amitgilad3)
- https://github.com/apache/iceberg-rust/issues/624 (thanks @Xuanwo)

I am sure I missed a few - please feel free to extend.

My proposal for a way forward would be as follows:
1. It would be great to get some eyes on on the already open PRs - I think especially  https://github.com/apache/iceberg-rust/pull/349 deserves some attention.
2. If there are any issues that are ready to be implemented from the list above - that nobody else is working on already, it would be great to highlight a few as an answer to this post that people can take and start working on. Maybe @Xuanwo, @liurenjie1024, @Fokko you have an overview?
3. We will have the first Iceberg Rust Community sync shortly on 28th of November! ([Public Google Calendar](https://calendar.google.com/calendar/u/0?cid=NzU4MDlhY2YwMTc2NjA2ODQwZjRhZjUxNjk0NjMzNjNlMTFiYzM5NWI3YzI2YmEyZGQxZDRjNjJhZjQyZjFkY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t), [Mailing List](https://lists.apache.org/thread/0t1w33jg9gmcwfnx9fplq48h1d4kjfn9)). In my opinion this would be a great opportunity to align on next steps and maybe hand out some tasks.

Let me know what you think!

@adisheshkishore, @amitgilad3, @JanKaul, @jaychia, @kevinzwang, @mkarbo, @mehmetozsoy-synnada, @rampage644, @twuebi

**Comment by sdd** [comment]
I've been intending on switching focus from reads to writes once me delete file read support PR is merged. I'll do my best to attend the meet on the 28th (day before my birthday! 😁) and look forward to collaborating with whoever else gets involved to land writes in iceberg-rust!

**Comment by ZENOTME** [comment]
Thank @c-thiel for raising! I am also working on #340 and can send it as a PR soon. Recently, I will also dedicate more effort to writing support. I think #349 is the first step to writing support in iceberg-rust so welcome review.

**Comment by kevinzwang** [comment]
Thank you for compiling this @c-thiel @ZENOTME! I'm part of the Daft team and we're eagerly looking forward to write support. The tasks enumerated by @ZENOTME match our priorities well -- we would need at least appends, overwrites, and partitioned writes in order to migrate to iceberg-rust. 

Let me know if this is being worked on already, but one thing we'd like to see is a public interface for building and committing snapshots. Daft handles writing data itself, and would use iceberg-rust only for the metadata operations to commit a write. Since this could also be used by the iceberg-rust writer, it makes sense to to solidify that interface first.

Thanks for the work so far! We would love to further our collaboration on this, we'll also be at the community sync to discuss further.

**Comment by ZENOTME** [comment]
> Thank you for compiling this @c-thiel @ZENOTME! I'm part of the Daft team and we're eagerly looking forward to write support. The tasks enumerated by @ZENOTME match our priorities well -- we would need at least appends, overwrites, and partitioned writes in order to migrate to iceberg-rust.
> 
> Let me know if this is being worked on already, but one thing we'd like to see is a public interface for building and committing snapshots. Daft handles writing data itself, and would use iceberg-rust only for the metadata operations to commit a write. Since this could also be used by the iceberg-rust writer, it makes sense to to solidify that interface first.
> 
> Thanks for the work so far! We would love to further our collaboration on this, @jaychia and I will also be at the upcoming community sync to discuss more.

Hi @kevinzwang , recently I'm working on #340 #342 #343 to support delete write, partition write.

And #349 has merged, so I think now the iceberg-rust support to commit data file.

**Comment by Fokko** [comment]
@ZENOTME I missed this issue, sorry for that. Should we merge this one into #700 ?

**Comment by ZENOTME** [comment]
> @ZENOTME I missed this issue, sorry for that. Should we merge this one into #700 ?

Sure! I think these are more about the writer.

**Comment by Xuanwo** [comment]
Tracked at https://github.com/apache/iceberg-rust/issues/700
