### ISSUE TITLE
Tracking issues of aligning storage support with iceberg-java

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#408]
iceberg-java now supports

- [x] aws s3
- [ ] aliyun oss
- [ ] azure adlsv2
- [ ] gcp gcs
- [ ] hadoop hdfs

Although OpenDAL supports more storage services than this, it still makes sense to at least support all existing storage services. This issue will track the progress.

---

After this been implemented, iceberg-rust will have the same storage support level as iceberg-java. I'm willing implement those features but also open to help review related changes. Please comment if you want to join the development and pick up one of them.

**Comment by Xuanwo** [comment]
cc @liurenjie1024, I'm not sure about your 0.3 release plan going. Maybe we can include this one inside?

**Comment by Xuanwo** [comment]
> I'm just curious how to test against these? Or maybe we can start with declaring these features as experimental.

- [x] aws s3: tested by minio now. We can add real s3 bucket in with sponsor.
- [ ] aliyun oss: Need an oss bucket (better to locate near us-east-1)
- [ ] azure adlsv2: can be tested by [Azurite](https://github.com/Azure/Azurite). And I'm willing to provide test infra as Microsoft MVP.
- [ ] gcp gcs: need a gcs bucket (better to locate near us-east-1)
- [ ] hadoop hdfs: can setup in CI directly (thanks open source!)

**Comment by sdd** [comment]
I have a question on the current `FileIO` - @Xuanwo is probably the right person to ask here.

It would be useful to be able to customize the OpenDAL `Operator` by being able to attach layers. Could we extend expose this capability somewhere? I've more than happy to work on this.

**Comment by Xuanwo** [comment]
> It would be useful to be able to customize the OpenDAL `Operator` by being able to attach layers. Could we extend expose this capability somewhere? I've more than happy to work on this.

Any detailed ideas? Are you talking about enable some existing [layers](https://docs.rs/opendal/latest/opendal/layers/index.html) for opendal or allow users to implement something new based on FileIO?

**Comment by Xuanwo** [comment]
> I agree that we can label these features as experimental. Setting up the CI infrastructure requires time, more so than implementing those features.

Split into a new issue: https://github.com/apache/iceberg-rust/issues/410

**Comment by jsimbadev** [comment]
@Xuanwo I can take the Azure datalake FileIO Implementation + the corresponding infrastructure set up, sound ok?

**Comment by Xuanwo** [comment]
> @Xuanwo I can take the Azure datalake FileIO Implementation + the corresponding infrastructure set up, sound ok?

Welcome, have fun!

**Comment by Xuanwo** [comment]
> cc @Xuanwo Do you still plan to finish this before in 0.3.0? Or we can postpone it to next release?

There are some more work to do at opendal side. I believe we can let 0.3.0 go first.
