### ISSUE TITLE
Tracking issues of storage backend integration tests

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#410]
> I'm just curious how to test against these? Or maybe we can start with declaring these features as experimental.

- [x] aws s3: tested by minio now. We can add real s3 bucket in with sponsor.
- [ ] aliyun oss: need an oss bucket (better to locate near us-east-1)
- [ ] azure adlsv2: can be tested by [Azurite](https://github.com/Azure/Azurite). And I'm willing to provide test infra as Microsoft MVP.
- [ ] gcp gcs: need a gcs bucket (better to locate near us-east-1)
- [ ] hadoop hdfs: can setup in CI directly (thanks open source!)

I agree that we can label these features as experimental. Setting up the CI infrastructure requires time, more so than implementing those features.

_Originally posted by @Xuanwo in https://github.com/apache/iceberg-rust/issues/408#issuecomment-2178730480_

**Comment by jdockerty** [comment]
@Xuanwo I can take a shot at GCP GCS if nobody else is working on that at the moment 👍

**Comment by jdockerty** [comment]
> How do you plan to do it? Is there any open source containers that could mock gcs?

@liurenjie1024 

There is this mock which I found earlier: https://github.com/fsouza/fake-gcs-server

Failing this, my plan was to use an actual GCS bucket for testing the functionality - given this was mentioned at being potentially [experimental for now](https://github.com/apache/iceberg-rust/issues/408#issuecomment-2178708441). Granted, this isn't ideal for CI, but the mock from above looks relatively well-used at first glance 👍
