### ISSUE TITLE
Tracking issues of iceberg rust v0.3.0 Release

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#543]
This issue is used to track tasks of the iceberg rust v0.3.0 release.

### Blockers

- [x] https://github.com/apache/iceberg-rust/issues/131
- [x] https://github.com/apache/iceberg-rust/issues/353
- [x] https://github.com/apache/iceberg-rust/issues/415
- [x] https://github.com/apache/iceberg-rust/issues/416

*Please leave comments if you think there are other issues that need to be included.*

#### GitHub Side

- [x] Bump version in project
- [x] Update docs
- [x] Generate dependencies list
- [x] Push release candidate tag to GitHub

#### ASF Side

- [x] Create an ASF Release
- [x] Upload artifacts to the SVN dist repo

### Voting

- [x] Start VOTE at iceberg community

### Official Release

- [x] Push the release git tag
- [x] Publish artifacts to SVN RELEASE branch
- [x] Change Iceberg Rust Website download link: https://github.com/apache/iceberg-rust/pull/573
- [x] Send the announcement

For details of each step, please refer to: https://rust.iceberg.apache.org/release

**Comment by sdd** [comment]
🙌🏼
