### ISSUE TITLE
Tracking issues of iceberg rust v0.4.0 Release

### ISSUE THREAD

**Issue by sungwy** [apache/iceberg-rust#739]
This issue is used to track tasks of the iceberg rust 0.4.0 release.

### Blockers

> Blockers are the tasks that must be completed before the release.

- [x] https://github.com/apache/iceberg-rust/issues/706 
- [x] https://github.com/apache/iceberg-rust/issues/694
- [x] https://github.com/apache/iceberg-rust/issues/663

The remaining issues listed under [0.4.0 Milestone](https://github.com/apache/iceberg-rust/milestone/3) do not seem like blockers, and could be tracked in the next release.

#### GitHub Side

- [x] Bump version in project: https://github.com/apache/iceberg-rust/pull/809
- [x] Update docs
- [x] Generate dependencies list
- [x] Push release candidate tag to GitHub

#### ASF Side

- [x] Create an ASF Release
- [x] Upload artifacts to the SVN dist repo

### Voting

- [ ] Start VOTE at iceberg community

### Official Release

- [x] Push the release git tag
- [x] Verify iceberg-rust release in Cargo and pyiceberg-core releases in PyPi
- [x] Publish artifacts to SVN RELEASE branch
- [x] Change Iceberg Rust Website download link
- [x] Send the announcement

For details of each step, please refer to: https://rust.iceberg.apache.org/release

**Comment by c-thiel** [comment]
@sungwy I think we should add https://github.com/apache/iceberg-rust/issues/694 to the blockers as well.
If we decide to not introduce a `SchemalessPartitionSpec`, we shouldn't release it as part of 0.4.0 as it would be a significant change to revert it.

**Comment by sungwy** [comment]
@c-thiel Hi Christian, thanks for flagging the issue! I've been tracking the discussion, and it looks like we are getting closer to a consensus on how we'd like to resolve the issue.

I will ensure the resolution gets taken into account within this release.

**Comment by Xuanwo** [comment]
It's better to include https://github.com/apache/iceberg-rust/pull/665 in. I'm working on this now.

**Comment by Xuanwo** [comment]
> @sungwy I think we should add #694 to the blockers as well. If we decide to not introduce a `SchemalessPartitionSpec`, we shouldn't release it as part of 0.4.0 as it would be a significant change to revert it.

Hi, @c-thiel, are you working on this now? I wish we can start the release work next week.

**Comment by c-thiel** [comment]
> > @sungwy I think we should add #694 to the blockers as well. If we decide to not introduce a `SchemalessPartitionSpec`, we shouldn't release it as part of 0.4.0 as it would be a significant change to revert it.
> 
> Hi @c-thiel, are you working on this now? I hope we can start the release process next week before Christmas; otherwise, we might have to see the new release until next year.

@Xuanwo 
I am talking with @Fokko  about this today. We'll try to come to a conclusion and post our findings in the issue.

**Comment by Xuanwo** [comment]
> @Xuanwo, @sungwy #694 is either fixed by leaving things as-is or by merging https://github.com/apache/iceberg-rust/pull/771 - see my comment at the top of the PR.

Thank you @c-thiel and @Fokko very much for working in this! 🙏

**Comment by sungwy** [comment]
Thank you for working on the issue @c-thiel and keeping this thread updated!

**Comment by Xuanwo** [comment]
> It's better to include #665 in. I'm working on this now.

Update: #665 is very close to get merging in.

**Comment by sungwy** [comment]
Also update on https://github.com/apache/iceberg-rust/issues/706 : I've investigated it and it looks like a non-issue. I'm waiting on the issue reporters to respond before closing it out

**Comment by sungwy** [comment]
It looks like two issues have been resolved, and https://github.com/apache/iceberg-rust/pull/771 is very close to being merged.

We'll get started with the release shortly! 🚀 

> I believe we need something like https://github.com/apache/opendal/blob/main/scripts/release.py to help generate ASF source tarballs for core and python binding.

Hi @Xuanwo - I started taking a look into this, and it looks like the existing [release.sh script](https://github.com/apache/iceberg-rust/blob/main/scripts/release.sh) would already create a tarball including all the source code for the core rust crates, as well as those of the python bindings.

The opendal reference implementation creates different tarballs for each binding and integrations separately, all including the the source code of the rust core crates as well.

Since we have [decided](https://lists.apache.org/thread/k71ls3pdf4x78r7q4x2np75tl74tsvdf) to have a single coupled release schedule for the rust core crates as well as the associated bindings, I'm wondering if it would just make sense to keep the source codes in the same tarball to simplify the process. We could also increment the version of pyiceberg_core library to 0.4.0 if that would make more sense for the tightly coupled release schedule.

I looked up the [ASF release policy](https://www.apache.org/legal/release-policy.html#source-packages), and I couldn't find any recommendations on how we should organize the source code for sub-distributions. I do see guidelines for how the source code needs to be uploaded and signed, and that the name of the packages will need to be prefixed by `apache` and the project name. I believe this will be the case whether we group the source code in a single tarball, or into separate ones.

I'm curious to hear your thoughts on this suggestion @Xuanwo @Fokko and @liurenjie1024 do you think uploading the source package as a single artifact would make sense in our case?

**Comment by Fokko** [comment]
I've cleaned up the milestone, and I think we're good to go 🚀 

@sungwy Since we release everything simultaneously, I would highly recommend putting everything in a single tarbal to keep things simple.

**Comment by Xuanwo** [comment]
Hi, @sungwy, I prefer to split them into different tarballs since they have different versions. However, I don't have a strong opinion on this. I believe it would be great to release them first and then refine the process in the next release.

**Comment by ZENOTME** [comment]
Should we merge #795 before release?

**Comment by Xuanwo** [comment]
Hi, I personally believe https://github.com/apache/iceberg-rust/pull/795 is not a blocker. Let's proceed with the release and avoid adding more PRs unless we have truly critical issues to address.

What do you think? cc @ZENOTME

**Comment by ZENOTME** [comment]
Both look good to me. According to https://github.com/apache/iceberg-rust/pull/795#discussion_r1884873126, this reorder will not happen if we use in avro format. In this release version, we don't expose the interface to let the user get the serializable representation,  so I think this issue will not affect the user in this version.🤔

**Comment by Xuanwo** [comment]
> Both look good to me. According to [#795 (comment)](https://github.com/apache/iceberg-rust/pull/795#discussion_r1884873126), this reorder will not happen if we use in avro format. In this release version, we don't expose the interface to let the user get the serializable representation, so I think this issue will not affect the user in this version.🤔

Thank you for your understanding. Let's continue addressing this issue without delaying the 0.4.0 release.

**Comment by sungwy** [comment]
Sounds good folks. I'll get started with the release.

Based on the discussion above, I think we are good to start the release, with the new Python binding included in the same source package.

Could someone help review this PR so we can get the versions synced to 0.4.0? https://github.com/apache/iceberg-rust/pull/808

**Comment by Xuanwo** [comment]
> Could someone help review this PR so we can get the versions synced to 0.4.0? #808

Merged. Let's move!

**Comment by sungwy** [comment]
Let's get this party started~! 🎈 

Here's the PR to remove deprecated functions, and bump the version of iceberg-rust for review: https://github.com/apache/iceberg-rust/pull/809

**Comment by Xuanwo** [comment]
Hi, @sungwy, https://github.com/apache/iceberg-rust/pull/826 has been fixed. Would you like to start a new rc instead?

**Comment by sungwy** [comment]
Yes, I'm on it 🖖
