### ISSUE TITLE
[EPIC] Support Puffin file format

### ISSUE THREAD

**Issue by fqaiser94** [apache/iceberg-rust#744]
# Why

There has been increased interest in Iceberg's [Puffin file format](https://iceberg.apache.org/puffin-spec/) recently. This is partially driven by the fact that the Iceberg V3 Spec added [support for deletion vectors](https://github.com/apache/iceberg/pull/11240) which are expected to be stored in Puffin files. 

However, as was recently [noted on the dev-list](https://lists.apache.org/thread/n46rz5d1xjffcfzrdt9p157y2vzbf583), currently only the iceberg-java SDK supports reading or writing Puffin files. Iceberg-rust itself has zero support for the Puffin file format today. The purpose of this ticket is to change that by adding support for Puffin to iceberg-rust _and_ iceberg-python (through exposed bindings). 

# How

I have already raised a PR for adding Puffin support to iceberg-rust here: https://github.com/apache/iceberg-rust/pull/714. However as that PR is quite large, I am splitting up the code and submitting it as multiple PRs in the following order: 
- [x] https://github.com/apache/iceberg-rust/pull/745
- [x] https://github.com/apache/iceberg-rust/pull/789
- [x] https://github.com/apache/iceberg-rust/pull/765
- [x] https://github.com/apache/iceberg-rust/pull/892
- [x] https://github.com/apache/iceberg-rust/pull/959
- [x] https://github.com/apache/iceberg-rust/pull/1165
- [ ] ~feat(puffin): Add Python bindings~
  - Let's wait for someone to request this feature first. I already see iceberg-python has started work on it's own [Puffin implementation](https://github.com/apache/iceberg-python/blob/15887011cb6bae9a4408eedc2824133efa3e1599/pyiceberg/table/puffin.py#L1). 
- [ ] ~Optimize puffin file metadata parsing (see [comment](https://github.com/apache/iceberg-rust/pull/765#discussion_r1885020961) for more details)~
  - Moved into a separate ticket: https://github.com/apache/iceberg-rust/issues/1198

**Comment by fqaiser94** [comment]
Can someone assign this ticket to me to avoid confusion?

**Comment by waynexia** [comment]
We have also implemented a puffin inside greptimedb (https://github.com/GreptimeTeam/greptimedb/tree/main/src/puffin), would like to push this forward together 🍻

**Comment by fqaiser94** [comment]
Going to close this ticket as IMO the major pieces are complete (feel free to reopen if you disagree). 

@liurenjie1024 it would be great if you could add this to the 0.5.0 milestone (for better visibility).
